### ISSUE TITLE
Handle download subfolders 

### ISSUE THREAD

**Issue by aubade** [Rudd-O/seedboxtools#10]
I like to sort different types of files (e.g. Linux Distro ISOs, and Archive.org letsplays), into separate subfolders (e.g. $SEEDBOXHOME/Downloads/LinuxISO and $SEEDBOXHOME/Downloads/AchiveOrgLP).

This currently seems to confuse leechtorrents, which expects everything to be in $SEEDBOXHOME/Downloads itself, and it says the torrents have had  their files removed. Is there any way it could be smarter about this and, ideally, mirror the subfolder structure in the local download directory?

**Comment by Rudd-O** [comment]
If you don't remove the `.*.done` files from the download folder, leechtorrents won't complain and won't redownload.

We only mirror the structure of the server itself.  If the server has dirs/files `a/*` and `b.mov`, that is what you will get in the download folder — `a/*` and `b.mov`.

**Comment by Rudd-O** [comment]
To auto-organize files in specific folders, I like to use this: https://github.com/Rudd-O/organizer

Unfortunately it only knows about movies / music / TV shows.  It could easily gain other types of medias via pull requests tho.
