### ISSUE TITLE
Windows 7 localmachine

### ISSUE THREAD

**Issue by earthcoder** [Rudd-O/seedboxtools#4]
Hello i have managed to install the tools on my windows 7 machine but i dont know how  to run configleecher  
when i type it in cmd i get
'configleecher' is not recognized as an internal or external command,
operable program or batch file.

so i tried 
python: can't open file 'configleecher': [Errno 2] No such file or directory

im quite new to python can you explain how to run it on a local machine windows 7

also i use ultraseedbox vps do you know if i need to set anything up on there its using rutorrent

many thanks

**Comment by Rudd-O** [comment]
Did that work?

I am closing the issue speculatively presuming that the advice worked.
