### ISSUE TITLE
leechtorrent errors 

### ISSUE THREAD

**Issue by dgiffen** [Rudd-O/seedboxtools#6]
Starting download of finished torrents
Traceback (most recent call last):
  File "/usr/local/bin/leechtorrents", line 10, in <module>
    sys.exit(mainloop())
  File "/usr/local/lib/python2.7/dist-packages/seedboxtools/leecher.py", line 167, in mainloop
    retvalue = do_guarded()
  File "/usr/local/lib/python2.7/dist-packages/seedboxtools/leecher.py", line 151, in do_guarded
    remove_finished=opts.remove_finished
  File "/usr/local/lib/python2.7/dist-packages/seedboxtools/leecher.py", line 12, in download
    for torrent, status, filename in client.get_files_to_download():
  File "/usr/local/lib/python2.7/dist-packages/seedboxtools/clients.py", line 45, in get_files_to_download
    torrents = self.get_finished_torrents()
  File "/usr/local/lib/python2.7/dist-packages/seedboxtools/clients.py", line 241, in get_finished_torrents
    assert r.status_code == 200, "Non-OK status code while retrieving get_finished_torrents: %r"%r.status_code
AssertionError: Non-OK status code while retrieving get_finished_torrents: 404

I have a PulsedMedia seedbox and am running Ubuntu 12.04

**Comment by Rudd-O** [comment]
Thanks.  I will look into it soon.

On 01/01/2015 05:43 AM, dgiffen wrote:
>
> Starting download of finished torrents
> Traceback (most recent call last):
> File "/usr/local/bin/leechtorrents", line 10, in
> sys.exit(mainloop())
> File "/usr/local/lib/python2.7/dist-packages/seedboxtools/leecher.py",
> line 167, in mainloop
> retvalue = do_guarded()
> File "/usr/local/lib/python2.7/dist-packages/seedboxtools/leecher.py",
> line 151, in do_guarded
> remove_finished=opts.remove_finished
> File "/usr/local/lib/python2.7/dist-packages/seedboxtools/leecher.py",
> line 12, in download
> for torrent, status, filename in client.get_files_to_download():
> File "/usr/local/lib/python2.7/dist-packages/seedboxtools/clients.py",
> line 45, in get_files_to_download
> torrents = self.get_finished_torrents()
> File "/usr/local/lib/python2.7/dist-packages/seedboxtools/clients.py",
> line 241, in get_finished_torrents
> assert r.status_code == 200, "Non-OK status code while retrieving
> get_finished_torrents: %r"%r.status_code
> AssertionError: Non-OK status code while retrieving
> get_finished_torrents: 404
>
> I have a PulsedMedia seedbox and am running Ubuntu 12.04
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Rudd-O/seedboxtools/issues/6>.
>

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by Rudd-O** [comment]
Does this still happen with the latest release?  I have submitted some updates.  What seedbox provider are you using?

**Comment by dgiffen** [comment]
I don't know, I gave not tried it in sometime. I was using pulsed media
seedbox when I got the errors. I have switched to SeedStuff, but didn't
think your software was supported on that one. SeedStuff has implemented
bittorrent sync and it works very well.

Thank you for your time

Doug Giffen

**Comment by Rudd-O** [comment]
It could be supported if you wrote a module for it :-)

(hint hint!)

**Comment by Rudd-O** [comment]
Does the new version of seedboxtools as posted on Github work for you?

On 01/10/2015 02:42 PM, Manuel Amador (Rudd-O) wrote:
> Thanks.  I will look into it soon.
>
> On 01/01/2015 05:43 AM, dgiffen wrote:
>>
>> Starting download of finished torrents
>> Traceback (most recent call last):
>> File "/usr/local/bin/leechtorrents", line 10, in
>> sys.exit(mainloop())
>> File
>> "/usr/local/lib/python2.7/dist-packages/seedboxtools/leecher.py",
>> line 167, in mainloop
>> retvalue = do_guarded()
>> File
>> "/usr/local/lib/python2.7/dist-packages/seedboxtools/leecher.py",
>> line 151, in do_guarded
>> remove_finished=opts.remove_finished
>> File
>> "/usr/local/lib/python2.7/dist-packages/seedboxtools/leecher.py",
>> line 12, in download
>> for torrent, status, filename in client.get_files_to_download():
>> File
>> "/usr/local/lib/python2.7/dist-packages/seedboxtools/clients.py",
>> line 45, in get_files_to_download
>> torrents = self.get_finished_torrents()
>> File
>> "/usr/local/lib/python2.7/dist-packages/seedboxtools/clients.py",
>> line 241, in get_finished_torrents
>> assert r.status_code == 200, "Non-OK status code while retrieving
>> get_finished_torrents: %r"%r.status_code
>> AssertionError: Non-OK status code while retrieving
>> get_finished_torrents: 404
>>
>> I have a PulsedMedia seedbox and am running Ubuntu 12.04
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Rudd-O/seedboxtools/issues/6>.
>>
>
> -- 
>     Rudd-O
>     http://rudd-o.com/

-- 
    Rudd-O
    http://rudd-o.com/

**Comment by dgiffen** [comment]
I do not know. I switched to another seedbox and use btsync.
Thanks for thinking if me. My current provider is seedstuff. Is your stuff
comparable. I'd be glad to give it a try
Thanks
Doug

**Comment by Rudd-O** [comment]
I'd be super happy if you could add support for seedstuff to my
program.  It'd be super cool to have it.

**Comment by dgiffen** [comment]
I wish I could do that also. My skills are the occasional edit of scripts.
Bit torrent sync works really well and is very reliable.
Thanks
Doug
